# Generated by Django 4.2.5 on 2023-10-06 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upcomeing_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Subtitle', models.CharField(max_length=50)),
                ('Desc', models.TextField(max_length=500)),
                ('Due_Date', models.DateTimeField()),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='posted_date')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_Grade_9_student', models.BooleanField(default=False)),
                ('is_Grade_9_student_classA', models.BooleanField(default=False, verbose_name='Class A')),
                ('is_Grade_9_student_classB', models.BooleanField(default=False, verbose_name='Class B')),
                ('is_Grade_9_student_classC', models.BooleanField(default=False, verbose_name='Class C')),
                ('is_Grade_9_student_classD', models.BooleanField(default=False, verbose_name='Class D')),
                ('is_Grade_9_student_classE', models.BooleanField(default=False)),
                ('is_Grade_9_student_classF', models.BooleanField(default=False)),
                ('is_Grade_9_student_classG', models.BooleanField(default=False)),
                ('is_Grade_9_student_classH', models.BooleanField(default=False)),
                ('is_Grade_9_student_classI', models.BooleanField(default=False)),
                ('is_Grade_9_student_classJ', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_Grade_9_teacher', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classA', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classB', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classC', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classD', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classE', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classF', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classG', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classH', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classI', models.BooleanField(default=False)),
                ('is_Grade_9_teacher_classJ', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Admin_signal', models.BooleanField(default=False)),
                ('Teacher_signal', models.BooleanField(default=False)),
                ('Student', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='posted_date')),
                ('student_boolean', models.BooleanField(default=False)),
                ('userpost', models.ForeignKey(blank=True, default=None, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Headmin.post')),
                ('userpost', models.ForeignKey(blank=True, default=None, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
