# Generated by Django 4.2.5 on 2023-10-10 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Headmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Refiner_Illuminator_TagPostCounter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='about_me',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='accessTo_moderatorTools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='access_review_queues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='altruist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='cast_close_AND_Reopen_votes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='comment_everywhere_Priv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='commenter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='create_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='create_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='create_wiki_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='editPostTimeOfUser',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='edit_community_wiki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='edit_questions_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='established_user_Priv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='favorite_question_S',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='flag_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='helpful_close_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='helpful_flags_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_high_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='job_search_status',
            field=models.CharField(choices=[('looking_for_job', 'Actively looking right now'), ('open_but_not_looking', 'Open, but not actively looking'), ('not_interested_in_jobs', 'Not interested in jobs')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('CONTRCT', 'Contract'), ('InternShip', 'InternShip')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='lifeJacket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='logout_on_all_devices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='max_expierence_level',
            field=models.CharField(choices=[('Student', 'Student'), ('Junior', 'Junior'), ('Mid_Level', 'Mid Level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='min_expierence_level',
            field=models.CharField(choices=[('Student', 'Student'), ('Junior', 'Junior'), ('Mid_Level', 'Mid Level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='not_to_Display_Full_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='post_edit_inactive_for_six_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='posts_edited_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='prefered_technologies',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='media/isle.jpg', upload_to='profile_photos'),
        ),
        migrations.AddField(
            model_name='account',
            name='protect_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='q_edited_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='remove_new_user_restrictions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='reputation',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='review_close_votes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='send_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='set_bounties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='suggested_Edit_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='targeted_tag',
            field=models.CharField(default='Commenter', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='trusted_user_Priv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='view_close_votes_Priv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='voteDownPriv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='voteUpPriv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='voting_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='website_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
