# Generated by Django 4.2.5 on 2023-10-11 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_comment_author_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Admin_signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Teacher_signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='student_boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
