# Generated by Django 4.2.5 on 2023-10-11 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0013_post_admin_signal_post_student_post_teacher_signal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, default=None, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headadmin_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
