# Generated by Django 4.2.5 on 2023-10-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0002_alter_historicalanswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivRepNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='#', null=True)),
                ('for_if', models.CharField(default='', max_length=30)),
                ('date_created_PrivNotify', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type_of_PrivNotify', models.CharField(choices=[('EDIT_GOT_APPROVED', 'Edit Approved'), ('ANSWER_ACCEPT_REP_P', 'Answer Accept Rep Plus'), ('BOUNTY_AWARDED_REP_P', 'Bounty Award Rep Plus'), ('MY_ANSWER_UPVOTE_REP_P', 'Answered Answer Upvote Rep Plus'), ('QUESTION_DOWNVOTE', 'Question DownVote'), ('MY_QUESTION_UPVOTE_REP_P', 'Asked Question Upvote Rep Plus'), ('Privilege_Earned', 'Privilege Earned'), ('BADGE_EARNED', 'Badge Earned')], default='', max_length=30)),
                ('missingReputation', models.IntegerField(blank=True, default=0, null=True)),
                ('privilegeURL', models.URLField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('answer_priv_noti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.answer')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_priv_noti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.question')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_noti', models.CharField(choices=[('comment_answer', 'comment_answer'), ('question_comment', 'question_comment'), ('community_message', 'community_message'), ('question_edit', 'question_edit'), ('question_reopen_voted', 'Question ReOpen Voted'), ('question_suggested_edit', 'Question Suggested Edit'), ('NEW_ANSWER', 'New_Answer')], default='', max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('answer_noti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.answer')),
                ('noti_receiver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='noti_receiver', to=settings.AUTH_USER_MODEL)),
                ('question_noti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.question')),
            ],
        ),
    ]
