# Generated by Django 4.2.5 on 2023-10-10 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0002_alter_historicalanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputation',
            name='awarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reputation_awarded_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
