# Generated by Django 4.2.5 on 2023-10-06 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Headmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_9_Student',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Grade_9_student_classA_A', models.BooleanField(default=False)),
                ('Grd9_ClsA_std_profile_picture', models.ImageField(upload_to='Student/Grade9/Grd9ClassA/Grd9ClsAProPic/')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('Resident', models.CharField(max_length=100)),
                ('Main_score', models.IntegerField(default=1)),
                ('English_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('English_score1', models.IntegerField(blank=True, default=0, null=True)),
                ('English_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('English_score2', models.IntegerField(blank=True, default=0, null=True)),
                ('English_name3', models.CharField(blank=True, max_length=200, null=True)),
                ('English_score3', models.IntegerField(blank=True, default=0, null=True)),
                ('English_score_sum', models.IntegerField(blank=True, default=0, null=True)),
                ('Math_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('Math_score1', models.IntegerField(blank=True, default=0, null=True)),
                ('Math_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('Math_score2', models.IntegerField(blank=True, default=0, null=True)),
                ('Math_name3', models.CharField(blank=True, max_length=200, null=True)),
                ('Math_score3', models.IntegerField(blank=True, default=0, null=True)),
                ('Math_score_sum', models.IntegerField(blank=True, default=0, null=True)),
                ('Science_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('Science_score1', models.IntegerField(blank=True, default=0, null=True)),
                ('Science_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('Science_score2', models.IntegerField(blank=True, default=0, null=True)),
                ('Science_name3', models.CharField(blank=True, max_length=200, null=True)),
                ('Science_score3', models.IntegerField(blank=True, default=0, null=True)),
                ('Science_score_sum', models.IntegerField(blank=True, default=0, null=True)),
                ('SocialScience_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('SocialScience_score1', models.IntegerField(blank=True, default=0, null=True)),
                ('SocialScience_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('SocialScience_score2', models.IntegerField(blank=True, default=0, null=True)),
                ('SocialScience_name3', models.CharField(blank=True, max_length=200, null=True)),
                ('SocialScience_score3', models.IntegerField(blank=True, default=0, null=True)),
                ('SocialScience_score_sum', models.IntegerField(blank=True, default=0, null=True)),
                ('PersonalDevelopment_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('PersonalDevelopment_score1', models.IntegerField(blank=True, default=0, null=True)),
                ('PersonalDevelopment_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('PersonalDevelopment_score2', models.IntegerField(blank=True, default=0, null=True)),
                ('PersonalDevelopment_name3', models.CharField(blank=True, max_length=200, null=True)),
                ('PersonalDevelopment_score3', models.IntegerField(blank=True, default=0, null=True)),
                ('PersonalDevelopment_score_sum', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Headmin.account',),
        ),
        migrations.CreateModel(
            name='Term_11_math_assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T1_A1_Maths_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('T1_A1_Maths_Desc', models.CharField(blank=True, max_length=100, null=True)),
                ('T1_A1_Maths_is_Test', models.BooleanField(default=False)),
                ('T1_A1_Maths_Marks', models.IntegerField(blank=True, default=0, null=True)),
                ('T1_A1_Maths_OutOfMarks', models.IntegerField(blank=True, default=0, null=True)),
                ('T1_A1_Maths_DatePosted', models.DateTimeField(blank=True, null=True, verbose_name='date posted')),
                ('student_user_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
